---
- name: arch | Capture Kernel Info Raw
  set_fact:
    kernel_info_raw: "{{ ansible_kernel.split('.') }}"

- name: arch | Setting Kernel Info
  set_fact:
    kernel_info: "{{ kernel_info_raw[0] + kernel_info_raw[1] }}"

- name: arch | Installing linux-headers
  pacman:
    name: "linux{{ kernel_info }}-headers"
    state: present
  become: true

- name: arch | Installing VirtualBox
  pacman:
    name: "{{ item }}"
    state: present
  become: true
  register: virtualbox_installed
  with_items:
    - "linux{{ kernel_info }}-virtualbox-host-modules"
    - virtualbox-guest-iso
    - virtualbox

- name: arch | Loading Virtualbox Module
  modprobe:
    name: vboxdrv
    state: present
  become: true
  when: virtualbox_installed['changed']