- name: redhat | Capture Current Kernel Release
  command: uname -r
  register: kernel_release
  changed_when: false

- name: redhat | Installing Pre-Reqs
  dnf:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - kernel-devel
    - "kernel-devel-{{ kernel_release['stdout'] }}"
    - kernel-headers
    - elfutils-libelf-devel
    - libselinux-python
  when: ansible_distribution == "Fedora"

- name: redhat | Installing Virtualbox
  dnf:
    name: "{{ virtualbox_dl_url }}/{{ virtualbox_fedora_package }}"
    state: present
  become: true
  when: ansible_distribution == "Fedora"
