---
- name: redhat | Capture Current Kernel Release
  command: uname -r
  register: kernel_release
  changed_when: false

- name: redhat | Installing Pre-Reqs
  dnf:
    name:
      [
        "kernel-devel",
        "{{ 'kernel-devel-' + kernel_release['stdout'] }}",
        "kernel-headers",
        "elfutils-libelf-devel",
        "libselinux-python",
      ]
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"

- name: redhat | Installing Virtualbox
  dnf:
    name: "{{ virtualbox_dl_url + '/' + virtualbox_fedora_package }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"
